[#ftl]
[#compress]
#include "cmsis_os.h"
[#list SWIPdatas as SWIP]
  [#if SWIP.variables??]
    [#list SWIP.variables as variable]
          [#if variable.name=="BinarySemaphores" ]
            [#assign s = variable.valueList]
            [#assign index = 0]
            [#list s as i]
              [#if index == 1]
                [#assign semaphoreAllocation = i]
              [/#if]
              [#assign index = index + 1]
            [/#list]
           [/#if]
        [#if variable.name=="Threads" ]
             [#assign s = variable.valueList]
             [#assign index = 0]
         [#list s as i]
          [#if index == 7]
          [#assign threadAllocation = i]
          [/#if]
          [#assign index = index + 1]
          [/#list]
           [/#if]
                 [#if variable.name=="Mutexes"]
                   [#assign s = variable.valueList]
                   [#assign index = 0]
                   [#list s as i]
                     [#if index == 1]
                       [#assign mutexAllocation = i]
                     [/#if]
                     [#assign index = index + 1]
                   [/#list]
                   [/#if]
                         [#if variable.name=="RecursiveMutexes"]
                           [#assign s = variable.valueList]
                           [#assign index = 0]
                           [#list s as i]
                             [#if index == 1]
                               [#assign RemutexAllocation = i]
                             [/#if]
                             [#assign index = index + 1]
                           [/#list]
                            [/#if]
      [#if variable.name=="Timers"]
        [#assign s = variable.valueList]
        [#assign index = 0]
        [#list s as m]
          [#if index == 6]
            [#assign timerAllocation = m]
          [/#if]
          [#assign index = index + 1]
        [/#list]
        [/#if]
           [#if variable.name=="Semaphores"]
             [#assign T = variable.valueList]
                [#assign index = 0]
                     [#list T as j]
                      [#if index == 2]
                      [#assign semaphoreAllocation1 = j]
                       [/#if]
                       [#assign index = index + 1]
                        [/#list]
                       [/#if]
              [#if variable.name=="Queues"]
                [#assign s = variable.valueList]
                [#assign index = 0]
                [#list s as l]
                  [#if index == 4]
                    [#assign queueAllocation = l]
                  [/#if]
                  [#assign index = index + 1]
                [/#list]
                [/#if]
                     [#if variable.name=="Events"]
                        [#assign s = variable.valueList]
                        [#assign index = 0]
                        [#list s as k]
                          [#if index == 1]
                            [#assign eventAllocation = k]
                          [/#if]
                          [#assign index = index + 1]
                        [/#list]
                        [/#if]
 [/#list]
   [#if (semaphoreAllocation?? && semaphoreAllocation=="Static") || (semaphoreAllocation1?? && semaphoreAllocation1 =="Static" ) || (eventAllocation?? && eventAllocation=="Static")|| (queueAllocation?? && queueAllocation=="Static")||(threadAllocation?? && threadAllocation=="Static")|| (mutexAllocation?? && mutexAllocation=="Static")|| (RemutexAllocation?? && RemutexAllocation=="Static")|| (timerAllocation?? && timerAllocation=="Static") ]
                 #include "FreeRTOS.h"
                [/#if]
[/#if]
[/#list]
[/#compress]
