[#ftl]
[#compress]

[#-----------------------------GENERATE EXTERN VARIABLES FOR DMA OF RIF-AWARE part  ------------------------------]
[#if RIF_AWARE?? ]
    [#assign lock = "false"]
    [#assign RTC_Flag = true]
    [#assign rtcPrivilegeFeatures=""]
    [#assign rtcPrivilegeFeaturesCount=1]
    [#assign backupRegisterPrivZone=""]
    [#assign rtcPrivilegeFull=""]
    [#list RIF_AWARE as ip ]
        [#list ip.entrySet() as entry]
            [#assign ipName=entry.key]
            [#assign ipData=entry.value]

            [#if ipName?matches("HPDMA1|GPDMA1")]
                [#list ipData  as value]
                    [#if !value.IP_Context?contains(Context)]
                        [#continue]
                    [/#if]

                    [#assign Channel =value.Feature?split(" ")]
                    [#if value.isHal=="true"]
                         extern DMA_HandleTypeDef handle_${Channel[0]}_Channel${Channel[2]} ;
                    [/#if]
                [/#list]
            [/#if]
        [/#list]
    [/#list]
[/#if ]
[/#compress]