[#ftl]
#n
[#--RIFPROT(rifid, sem_list, lock, sec, priv, scid, sem_en, cfen)--]
[#macro bind_RISUP	pElmt pDtLevel]
[#local Tabulation=dts_get_tabs(pDtLevel)]
[#local TABnode = Tabulation.TABN]
[#local TABprop = Tabulation.TABP]
[#local semListUIIndex=0]
[#local secUIIndex=semListUIIndex+1]
[#local privUIIndex=secUIIndex+1]
[#local lockUIIndex=privUIIndex+1]
[#assign OmmanagerProp=["OCTOSPI1","OCTOSPI2","OCTOSPIM","OTFDEC1","OTFDEC2"]]
[#assign elmtsListIpMcuboot= srvcmx_getListIpMcuboot()]
[#if !(srvcmx_isTargetedFw_inDTS("OP-TEE") && mx_tdcidContext?matches("M[0-9][0-9].*"))][#-- remove RISUP from OP-TEE when CM33TDCID--]
&rifsc {
${TABprop}st,protreg = <
[#if srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*")&& mx_socDtRPN?matches("stm32mp21")]
${TABprop}${TABprop}RIFPROT(STM32MP21_RIFSC_RESERVED_91_ID, RIF_CID1_BF|RIF_CID2_BF, RIF_LOCK, RIF_SEC, RIF_PRIV, RIF_UNUSED, RIF_SEM_EN, RIF_CFEN)
[/#if]
    [#list mx_RIF_Params.entrySet() as RIF_Params]
        [#if (RIF_Params.key)?? && RIF_Params.key == "RISUP"]
            [#local RISUP = RIF_Params.value]
            [#list RISUP.entrySet() as RISUP_Params]
                [#-- Columns Formatting Begin --]
                [#compress]
                [#local RISUP_Formatted = RISUP_Params.value[1..]]	[#--remove ID from the list, not used in code gen ("1" represents used List start index ) --]
                [#-- RISUP_Formatted= CID_list~sem_list, sec, priv, lock --]
                [#local isCIDmatchesInt = RISUP_Formatted[semListUIIndex]?matches("[123456789]")]
                [#local isCIDZero = RISUP_Formatted[semListUIIndex]=="-"]
                [#-- Adding scid --]
                [#if isCIDmatchesInt]
                    [#local  RISUP_Formatted = srvcmx_isContextMcuBoot(RISUP_Params.key)?then(RISUP_Formatted+["RIF_CID2"],RISUP_Formatted+["RIF_CID"+RISUP_Formatted[semListUIIndex]])]
                [#else]
               		 [#if srvcmx_isTargetedFw_inDTS("MCUBOOT")]
                             [#local  RISUP_Formatted =  RISUP_Formatted+["RIF_CID2"]]
                      [#else]
                    [#local  RISUP_Formatted =  RISUP_Formatted+["RIF_UNUSED"]]
                     [/#if]
                [/#if]

                [#-- Formatting sem_list --]
                [#if isCIDZero]
                    [#local RISUP_Formatted=["EMPTY_SEMWL"] + RISUP_Formatted[secUIIndex..]]
                [#elseif isCIDmatchesInt]
                    [#local RISUP_Formatted=["RIF_UNUSED"] + RISUP_Formatted[secUIIndex..]]
                [#elseif RISUP_Formatted[semListUIIndex]?contains("&")]
                    [#local CID = ""]
                    [#list RISUP_Formatted[semListUIIndex]?split("&") as CIDx]
                        [#local CID =CID + "RIF_CID"+ CIDx +"_BF|"]
                    [/#list]
                    [#local CID =CID?remove_ending("|")]
                     [#if srvcmx_isTargetedFw_inDTS("MCUBOOT")]
                     [#local CID =CID?replace("RIF_CID1_BF|RIF_CID2_BF","RIF_UNUSED")]
                     [/#if]
                    [#local RISUP_Formatted =  [CID] + RISUP_Formatted[secUIIndex..]]
                [/#if]

                [#-- Formatting sec --]
                [#if isCIDZero]
                    [#local RISUP_Formatted = [RISUP_Formatted[secUIIndex-1]] + ["RIF_NSEC"] + RISUP_Formatted[(secUIIndex+1)..]]
                [#else]
                    [#if srvcmx_isTargetedFw_inDTS("MCUBOOT")]
                        [#local RISUP_Formatted = [RISUP_Formatted[secUIIndex-1]] + ["RIF_SEC"] + RISUP_Formatted[(secUIIndex+1)..]]
                    [#else]
                        [#local RISUP_Formatted = [RISUP_Formatted[secUIIndex-1]] + [(RISUP_Formatted[secUIIndex]=="true")?then("RIF_SEC","RIF_NSEC")] + RISUP_Formatted[(secUIIndex+1)..]]
                    [/#if]
                [/#if]
                [#-- Formatting priv --]
                [#if srvcmx_isTargetedFw_inDTS("MCUBOOT")]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..(privUIIndex-1)] + ["RIF_PRIV"] + RISUP_Formatted[(privUIIndex+1)..]]
                [#else]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..(privUIIndex-1)] + [(RISUP_Formatted[privUIIndex]== "true")?then("RIF_PRIV","RIF_NPRIV")] + RISUP_Formatted[(privUIIndex+1)..]]
                [/#if]
                [#-- Formatting lock --]
                [#if srvcmx_isTargetedFw_inDTS("MCUBOOT")]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..(lockUIIndex-1)] + ["RIF_UNLOCK"] + RISUP_Formatted[(lockUIIndex+1)..]]
                [#else]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..(lockUIIndex-1)] + [(RISUP_Formatted[lockUIIndex]== "true")?then("RIF_LOCK","RIF_UNLOCK")] + RISUP_Formatted[(lockUIIndex+1)..]]
                [/#if]
                [#-- Adding sem_en --]
                [#if isCIDZero]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..4] + [(RISUP_Formatted[semListUIIndex]== "EMPTY_SEMWL")?then("RIF_SEM_EN","RIF_SEM_DIS")] ]
                [#else]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..4] + [(RISUP_Formatted[semListUIIndex]== "RIF_UNUSED")?then("RIF_SEM_DIS","RIF_SEM_EN")] ]
                [/#if]
                [#-- Adding cfen --]
                [#if isCIDZero ||(RISUP_Formatted[5] == "RIF_SEM_EN")||((RISUP_Formatted[5] == "RIF_SEM_DIS")&&(RISUP_Formatted[4]?matches("RIF_CID\\d")))]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..5] + ["RIF_CFEN"] ]
                [#elseif (RISUP_Formatted[semListUIIndex]== "RIF_UNUSED")&&(RISUP_Formatted[4]=="RIF_UNUSED")]
                    [#local RISUP_Formatted = RISUP_Formatted[semListUIIndex..5] + ["RIF_CFDIS"] ]
                [/#if]

                [#-- swapping lock, sec, priv  from RIFPROT(rifid, sem_list, "sec", "priv", "lock", scid, sem_en, cfen) to RIFPROT(rifid, sem_list, "lock", "sec", "priv", scid, sem_en, cfen)  --]
                [#local RISUP_Formatted = [RISUP_Formatted[semListUIIndex]] +[RISUP_Formatted[lockUIIndex]] +[RISUP_Formatted[secUIIndex]] +[RISUP_Formatted[privUIIndex]] +RISUP_Formatted[4..]]

                [#-- Columns Formatting END--]
                [/#compress]
                [#--displaying RIFPROT macro --]
                [#local RISUP_values =""]
                [#list RISUP_Formatted as RISUP_Params_values]
                        [#if RISUP_Params_values?has_next]
                            [#local RISUP_values += RISUP_Params_values + ", "]
                        [#else]
                            [#local RISUP_values += RISUP_Params_values]
                        [/#if]
                [/#list]
                [#if mx_socDtRPN?matches("stm32mp21") && !srvcmx_isTargetedFw_inDTS("MCUBOOT")  ]
${TABprop}${TABprop}RIFPROT(${mx_socDtRPN?upper_case}_RIFSC_${RISUP_Params.key}_ID, ${RISUP_values})
                [#elseif !OmmanagerProp?seq_contains(RISUP_Params.key) &&  mx_socDtRPN?matches("stm32mp23") ]
                    [#if !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
${TABprop}${TABprop}RIFPROT(STM32MP25_RIFSC_${RISUP_Params.key}_ID, ${RISUP_values})
                    [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && elmtsListIpMcuboot?seq_contains(RISUP_Params.key)][#-- for MCUBOOT we generate only features assigned to CID2--]
${TABprop}${TABprop}RIFPROT(STM32MP25_RIFSC_${RISUP_Params.key}_ID, ${RISUP_values})
                    [/#if]
                [#elseif !OmmanagerProp?seq_contains(RISUP_Params.key)]
                    [#if !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
${TABprop}${TABprop}RIFPROT(${mx_socDtRPN?upper_case}_RIFSC_${RISUP_Params.key}_ID, ${RISUP_values})
                    [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") &&  elmtsListIpMcuboot?seq_contains(RISUP_Params.key)][#-- for MCUBOOT we generate only features assigned to CID2--]
${TABprop}${TABprop}RIFPROT(${mx_socDtRPN?upper_case}_RIFSC_${RISUP_Params.key}_ID, ${RISUP_values})
                    [/#if]
                [/#if]
		    [/#list]
	    [/#if]
    [/#list]
${TABprop}>;
[/#if]
[/#macro]

[#macro bind_RIMU pElmt pDtLevel]
[#local Tabulation=dts_get_tabs(pDtLevel)]
[#local TABnode = Tabulation.TABN]
[#local TABprop = Tabulation.TABP]
[#local RimuIdUIIndex=0]
[#local CIDUIIndex=1]
[#local MasterCIDUIIndex=2]
[#local SecureUIIndex=3]
[#local PrivilegeUIIndex=4]
[#local CID2_exist=false]
[#if !(srvcmx_isTargetedFw_inDTS("OP-TEE") && mx_tdcidContext?matches("M[0-9][0-9].*")) ][#-- remove RISUP from OP-TEE when CM33TDCID--]
[#list mx_RIF_Params.entrySet() as RIF_Params]
	[#if (RIF_Params.key)?? && RIF_Params.key == "RIMU"]
		[#local RIMU_Formatted = RIF_Params.value]
		[#list RIMU_Formatted.entrySet() as RIMU_Params]
             [#if  RisupMcuBootMap.entrySet()?contains(RIMU_Params.key)]
                [#local CID2_exist= true]
            [/#if]
		[/#list]
		[#if srvcmx_isTargetedFw_inDTS("MCUBOOT") && CID2_exist]
${TABprop}st,rimu = <
        [#elseif !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
${TABprop}st,rimu = <
        [/#if]
		[#list RIMU_Formatted.entrySet() as RIMU_Params]
		    [#if srvcmx_isTargetedFw_inDTS("MCUBOOT") &&  elmtsListIpMcuboot?seq_contains(RIMU_Params.key)][#-- for MCUBOOT we generate only features assigned to CID2--]
${TABprop}${TABprop}RIMUPROT(RIMU_ID(${RIMU_Params.value[RimuIdUIIndex]}), RIF_CID2, RIF_SEC, ${(RIMU_Params.value[PrivilegeUIIndex]=="true")?then("RIF_PRIV","RIF_NPRIV")},${(RIMU_Params.value[CIDUIIndex]=="true")?then("RIF_CIDSEL_M","RIF_CIDSEL_P")}) /* RIMU IP = ${RIMU_Params.key} */
		    [#elseif !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
${TABprop}${TABprop}RIMUPROT(RIMU_ID(${RIMU_Params.value[RimuIdUIIndex]}), ${(RIMU_Params.value[MasterCIDUIIndex]=="-" || RIMU_Params.value[CIDUIIndex]=="false")?then("RIF_UNUSED","RIF_CID"+ RIMU_Params.value[2])}, ${(RIMU_Params.value[SecureUIIndex]=="true")?then("RIF_SEC","RIF_NSEC")}, ${(RIMU_Params.value[PrivilegeUIIndex]=="true")?then("RIF_PRIV","RIF_NPRIV")},${(RIMU_Params.value[CIDUIIndex]=="true")?then("RIF_CIDSEL_M","RIF_CIDSEL_P")}) /* RIMU IP = ${RIMU_Params.key} */
		    [/#if]
		[/#list]
	[/#if]
[/#list]
[#if srvcmx_isTargetedFw_inDTS("MCUBOOT") && CID2_exist]
${TABprop}>;
[#elseif !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
${TABprop}>;
[/#if]
[#if mx_isAhbErrata && !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
${TABprop}st,errata-ahbrisab;
[/#if]
[/#if]
[/#macro]

[#macro bind_GLOCK pElmt pDtLevel]
[#local MasterCIDUIIndex=2]
[#local CID2_exist=false]
[#local Tabulation=dts_get_tabs(pDtLevel)]
[#local TABnode = Tabulation.TABN]
[#local TABprop = Tabulation.TABP]
[#if !(srvcmx_isTargetedFw_inDTS("OP-TEE") && mx_tdcidContext?matches("M[0-9][0-9].*"))] [#-- remove RISUP from OP-TEE when CM33TDCID--]
[#list mx_RIF_Params.entrySet() as RIF_Params]
    [#if (RIF_Params.key)?? && RIF_Params.key == "RIMU"]
		[#local RIMU_Formatted = RIF_Params.value]
		[#list RIMU_Formatted.entrySet() as RIMU_Params]
            [#if RIMU_Params.value[MasterCIDUIIndex]=="2"]
                [#local CID2_exist= true]
            [/#if]
		[/#list]
    [/#if]
	[#if (RIF_Params.key)?? && RIF_Params.key == "GLOCK"]
		[#list RIF_Params.value.entrySet() as GLOCK_Params]
		[#local globalLock = GLOCK_Params.value]
			[#if (GLOCK_Params.key)?? && GLOCK_Params.key == "RIMU_GLOCK"]
                [#if !srvcmx_isTargetedFw_inDTS("MCUBOOT")]
 ${TABprop}${(globalLock[0]=="true")?then("st,glocked = <RIFSC_RIMU_GLOCK>;","")}
                [/#if]
			[/#if]
			[#--[#if (GLOCK_Params.key)?? && GLOCK_Params.key == "RISUP_GLOCK"]--]
[#--${TABnode}${(globalLock[0]=="true")?then("st,glocked = <RIFSC_RISUP_GLOCK>;","")}--]
			[#--[/#if]--]
		[/#list]
	[/#if]
[/#list]
${TABprop}status = "okay";
#n
${TABprop}/* USER CODE BEGIN rifsc */
${TABprop}/* USER CODE END rifsc */
};
[/#if]
[/#macro]
