[#ftl]
[#macro bind_gpiosc	pElmt pDtLevel]
	[#compress]
		[#local SecuredPorts=[]]
		[#local Tabulation=dts_get_tabs(pDtLevel)]
		[#local TABnode = Tabulation.TABN]
		[#local TABprop = Tabulation.TABP]
		[#list mx_peripheralGPIOParams.entrySet() as IpSignalMap]
				[#local signalsDescription=IpSignalMap.value]
				[#list signalsDescription.entrySet() as signalDesc]
					[#if	signalDesc.value??]
						[#local SignalDescValue=signalDesc.value]
						[#list SignalDescValue?keys as IoKey]
							[#if IoKey=="PinAttribute" ]
							    [#assign pinAttribute=SignalDescValue[IoKey]?split(",")]
								[#--filtering IOs that needs to be secured--]
								[#--RCC signals are specific, we don't generate their pinctrl in linux--]
							    [#if (!pinAttribute?seq_contains("CortexA7NS") || signalDesc.key?matches("RCC_MCO_[1-9]") || signalDesc.key?matches("I2S_CKIN") )&& (pinAttribute?seq_contains("BootROM") || pinAttribute?seq_contains("CortexA7S") || pinAttribute?seq_contains("BootLoader") )]
                                    [#if (mx_socDtRPN == "stm32mp15")]
										[#if (SignalDescValue["Pin"])?starts_with("PZ")]
											[#local SecuredPorts += [SignalDescValue["Pin"]]]
										[/#if]
									[#else]
										[#local SecuredPorts += [SignalDescValue["Pin"]]]
									[/#if]
							    [/#if]
							[/#if]
						[/#list]
					[/#if]
				[/#list]
		[/#list]
		[#local SecPortsMap = {}]
		[#local PortsIndex = []]
		[#list SecuredPorts?sort as SecPort]
			[#if (SecPortsMap[SecPort?substring(0,2)])??]
				[#local PortsIndex = SecPortsMap[SecPort?substring(0,2)]]
			[#else]
				[#local PortsIndex = []]
			[/#if]
			[#local   PortsIndex+=[SecPort?keep_after("P[A-Z]","r")]]
			[#local SecPortsMap += {SecPort?substring(0,2):PortsIndex}]
		[/#list]
	[/#compress]
[#--For MP13 all IOs assigned to !CortexA7NS && (all other SW contexts) needs to be secured in OP-TEE--]
[#--For MP15 only PZ IOs assigned to !CortexA7NS && (all other SW contexts) needs to be secured in OP-TEE--]
	[#list SecPortsMap?keys as PortName]
		[#local ProtregValue=""]
    	[#list SecPortsMap[PortName] as PortIndex]
	    	[#local ProtregValue+="TZPROT("+PortIndex+") | "]
	    [/#list]
${TABnode}&gpio${PortName?keep_after("P")?lower_case} {
${TABprop}st,protreg = < (${ProtregValue?keep_before_last(" | ")}) >;
${TABnode}};
#n
	[/#list]
[/#macro]
