
[#ftl]
[#assign Tabulation=dts_get_tabs(pDtLevel)]
[#assign TABnode = Tabulation.TABN]
[#assign TABprop = Tabulation.TABP]
[#assign index = 0]
[#assign FeatureIDUIIndex = index][#assign index += 1]
[#assign MasterCidUIIndex = index][#assign index += 1]
[#assign SecUIIndex = index][#assign index += 1]
[#assign PrivUIIndex = index][#assign index += 1]
[#assign LockUIIndex = index][#assign index += 1]
[#assign SystemModeUIIndex = index]
[#assign RifAwarePrefix = "RIFAware_"]
[#assign RifAwareExtraTablePrefix = "RIFAwareExtraTable_"]
[#assign RifAwareIPName=""]
[#assign RifAwareIPsWithSpeceficProp=["TAMP","HSEM","EXTI1","EXTI2"]]
[#assign RifAwareIPsWithNoAccess= ["FMC", "PWR", "RCC", "GPIO", "DSIHOST", "LTDC", "ETHSW", "HPDMA1", "HPDMA2", "HPDMA3","GPDMA1"]]
[#assign elmtsListFeatureGPIO= srvcmx_getListFeaturesGPIO()]
[#assign elmtsListFeatureWithoutGPIO = srvcmx_getListFeaturesName()]
[#list mx_RIF_Params.entrySet() as RIF_Params]
	[#if (RIF_Params.key)?? && RIF_Params.key?matches("^"+RifAwarePrefix+".+")]
		[#compress]
			[#assign RifAwareIPName=RIF_Params.key?keep_after(RifAwarePrefix)]
			[#assign RifAwareIPFeatures = RIF_Params.value]
			[#assign FeatureNamesList=[]]
			[#assign FeatureIDList=[]]
			[#assign MasterCIDList=[]]
			[#assign SecureList=[]]
			[#assign PrivilegeList=[]]
			[#assign SCIDList=[]]
			[#assign SemList=[]]
			[#assign FilteringCIDList=[]]
			[#assign LockList=[]]
			[#assign SystemModeList=[]]
			[#list RifAwareIPFeatures.entrySet() as RifAwareIPFeatureList]
				[#assign isCIDmatchesInt = RifAwareIPFeatureList.value[MasterCidUIIndex]?matches("[123456789]")]
				[#assign isCIDZero = RifAwareIPFeatureList.value[MasterCidUIIndex]=="-"]
				[#-- Populate FeatureNamesList --]
				[#assign FeatureNamesList+=[RifAwareIPFeatureList.key]]
				[#-- Populate FeatureIDList --]
				[#assign FeatureIDList+=[(RifAwareIPFeatureList.value[FeatureIDUIIndex])?matches("[0-9]\\d{0,9}")?then("("+RifAwareIPFeatureList.value[FeatureIDUIIndex]+")","_"+RifAwareIPFeatureList.value[FeatureIDUIIndex]?substring(0, 3)+"("+RifAwareIPFeatureList.value[FeatureIDUIIndex]?substring(3)+")")]]
				[#-- Populate MasterCIDList with formatted Master CIDs --]
				[#if RifAwareIPFeatureList.value[SystemModeUIIndex]?? && (RifAwareIPFeatureList.value[SystemModeUIIndex] == "true")]
				    [#if mx_tdcidContext?starts_with("A35") || RifAwareIPFeatureList.key?contains("SYSRAM_CFGR")]
                        [#assign MasterCIDList+=["RIF_CID1_BF"]]
                    [#else]
                        [#assign MasterCIDList+=["RIF_CID2_BF"]]
				    [/#if]
				[#elseif isCIDmatchesInt]
					[#if RifAwareIPFeatureList.value[SystemModeUIIndex]?? && (RifAwareIPFeatureList.value[SystemModeUIIndex] == "true")]
						[#assign MasterCIDList+=["RIF_CID"+RifAwareIPFeatureList.value[MasterCidUIIndex]+"_BF"]]
					[#else]
						[#assign MasterCIDList+=["RIF_UNUSED"]]
					[/#if]
				[#elseif isCIDZero ]
					[#if RifAwareIPsWithNoAccess?seq_contains(RifAwareIPName)]
						[#assign MasterCIDList+=["EMPTY_SEMWL"]]
					[#else]
						[#assign MasterCIDList+=["RIF_UNUSED"]]
					[/#if]
				[#elseif RifAwareIPFeatureList.value[MasterCidUIIndex]?contains("&")]
					[#assign MasterCID = ""]
					[#list RifAwareIPFeatureList.value[MasterCidUIIndex]?split("&") as CIDx]
						[#assign MasterCID +=  "RIF_CID"+ CIDx +"_BF|"]
					[/#list]
					[#assign MasterCIDList+=[MasterCID]]
				[/#if]
				[#-- Populate SecureList --]
				[#if isCIDZero]
					[#assign SecureList+= ["RIF_NSEC"]]
				[#else]
					[#assign SecureList+= [(RifAwareIPFeatureList.value[SecUIIndex]=="true")?then("RIF_SEC","RIF_NSEC")]]
				[/#if]
				[#-- Populate PrivilegeList --]
				[#assign PrivilegeList+= [(RifAwareIPFeatureList.value[PrivUIIndex]=="true")?then("RIF_PRIV","RIF_NPRIV")] ]
				[#assign SCIDList+= [(isCIDmatchesInt && !(RifAwareIPFeatureList.value[SystemModeUIIndex]?? && (RifAwareIPFeatureList.value[SystemModeUIIndex] == "true")))?then("RIF_CID"+RifAwareIPFeatureList.value[MasterCidUIIndex],"RIF_UNUSED")] ]
				[#-- Populate SemList --]
				[#if isCIDZero && RifAwareIPsWithNoAccess?seq_contains(RifAwareIPName) || RifAwareIPFeatureList.value[SystemModeUIIndex]?? && (RifAwareIPFeatureList.value[SystemModeUIIndex] == "true")]
					[#assign SemList+= ["RIF_SEM_EN"]]
				[#else]
					[#assign SemList+= [(RifAwareIPFeatureList.value[MasterCidUIIndex]?contains("&"))?then("RIF_SEM_EN","RIF_SEM_DIS")] ]
				[/#if]
				[#-- Populate FilteringCIDList --]
				[#if RifAwareIPsWithNoAccess?seq_contains(RifAwareIPName) && isCIDZero]
					[#assign FilteringCIDList+=["RIF_CFEN"]]
				[#else]
					[#assign FilteringCIDList+= [(RifAwareIPFeatureList.value[MasterCidUIIndex] == "-")?then("RIF_CFDIS","RIF_CFEN")] ]
				[/#if]

				[#if RifAwareIPName=="RCC"]
					[#assign LockList+= [(RifAwareIPFeatureList.value[LockUIIndex] == "true")?then("RIF_LOCK","RIF_UNLOCK")] ]
					[#assign  SystemModeList+= [(RifAwareIPFeatureList.value[SystemModeUIIndex] == "true")?then("true","false")] ]
				[/#if]
				[#if RifAwareIPFeatureList.value[LockUIIndex]?? && RifAwareIPName=="GPIO"]
				    [#assign LockList+= [(RifAwareIPFeatureList.value[LockUIIndex] == "true")?then("RIF_LOCK","RIF_UNLOCK")]]
				[#elseif !RifAwareIPFeatureList.value[LockUIIndex]?? && RifAwareIPName=="GPIO"]
				    [#assign LockList+= ["RIF_UNLOCK"]]
				[/#if]
			[/#list]
		[/#compress]
		[#if RifAwareIPName=="GPIO" ]
			[#assign PortsList=[]]
			[#list FeatureNamesList as PortName]
				[#if PortName?matches("P[ABCDEFGHIJKLMNOPQRSTUVWXYZ]\\d{0,99}")&& (!PortsList?seq_contains(PortName[1..<2]))]
				[#assign PortsList+=[PortName[1..<2]]]
				[/#if]
			[/#list]
			[#assign PortsListAssignedMCUBOOT=[]]
			[#list FeatureNamesList as PortName]
				[#list elmtsListFeatureGPIO as gpio]
					[#if gpio?seq_contains(PortName)]
						[#assign  PortsListAssignedMCUBOOT +=[PortName?substring(0,2)]]
					[/#if]
				[/#list]
			[/#list]
			[#list PortsList as Port]
		[#if srvcmx_isTargetedFw_inDTS("MCUBOOT")]
			[#assign  PortsLists =[]]
				[#list elmtsListFeatureGPIO as PortName]
					[#list PortName as pName]
						 [#assign  PortsList +=[pName]]
					[/#list]
				[/#list]
		[/#if]
#n
                [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
&${RifAwareIPName?lower_case}${Port?lower_case} {
                [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && PortsListAssignedMCUBOOT?seq_contains("P"+Port)]
&${RifAwareIPName?lower_case}${Port?lower_case} {
                [/#if]
#n
                [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
${TABnode}st,protreg = <
                [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && PortsListAssignedMCUBOOT?seq_contains("P"+Port)]
${TABnode}st,protreg = <
                [/#if]
				[#list FeatureNamesList as FeatureName]
					[#if FeatureName?matches("P"+Port+"\\d{0,99}")]
					    [#assign ParamPrefix="_IOPORT_PIN"]
                        [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
${TABprop}RIFPROT(RIF${ParamPrefix}${FeatureIDList[FeatureName?index]}, ${MasterCIDList[FeatureName?index]?keep_before_last("|")}, ${LockList[FeatureName?index]}, ${SecureList[FeatureName?index]}, ${PrivilegeList[FeatureName?index]}, ${SCIDList[FeatureName?index]}, ${SemList[FeatureName?index]}, ${FilteringCIDList[FeatureName?index]}) /* ${FeatureName} */
                        [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && PortsList?seq_contains(FeatureName)]
${TABprop}RIFPROT(RIF${ParamPrefix}${FeatureIDList[FeatureName?index]}, ${MasterCIDList[FeatureName?index]?keep_before_last("|")}, ${LockList[FeatureName?index]}, RIF_SEC, RIF_PRIV, RIF_CID2, ${SemList[FeatureName?index]}, ${FilteringCIDList[FeatureName?index]}) /* ${FeatureName} */
                        [/#if]
					[/#if]
				[/#list]
                [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
${TABnode}>;
[#--here to add specefic property : RifAwareIPName==HSEM?... --]
};
                [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && PortsListAssignedMCUBOOT?seq_contains("P"+Port)]
${TABnode}>;
};
                [/#if]
			[/#list]
		[#else]
#n
            [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*") && !RifAwareIPName?matches("HSEM"))]
[#--it will replace name only for rcc node otherwise it will keep rifawareIPName as it is--]
&${RifAwareIPName?lower_case?replace("rcc","rcc_rif")} {
                [#if RifAwareIPName?starts_with("HPDMA")]
#n
${TABnode}st,errata-ahbrisab;
                [/#if]
            [#elseif (srvcmx_isTargetedFw_inDTS("OP-TEE") && mx_tdcidContext?matches("A[0-9][0-9].*"))]
&${RifAwareIPName?lower_case} {
				[#if RifAwareIPName?starts_with("HPDMA")]
#n
${TABnode}st,errata-ahbrisab;
                [/#if]
            [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && (RifAwareIPName?starts_with("GPIO")||RifAwareIPName?starts_with("TAMP"))]
&${RifAwareIPName?lower_case} {
            [/#if]
            [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*") && !RifAwareIPName?matches("HSEM")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
#n
${TABnode}st,protreg = <
            [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && (RifAwareIPName?starts_with("GPIO"))]
#n
${TABnode}st,protreg = <
            [/#if]
			[#list FeatureNamesList as FeatureName]
				[#assign ParamPrefix="_RESOURCE"]
				[#if RifAwareIPName=="FMC"]
					[#assign ParamPrefix="_CTRL"]
				[/#if]
				[#if RifAwareIPName?starts_with("IPCC")]
					[#assign ParamPrefix="_"+FeatureName?substring(0,12)?upper_case?replace(" ","_")]
					[#assign RifAwareIPName="IPCC"]
				[/#if]
				[#if RifAwareIPName?starts_with("HPDMA")]
					[#assign ParamPrefix="_CHANNEL"]
					[#assign RifAwareIPName="HPDMA"]
				[/#if]
                [#if srvcmx_isTargetedFw_inDTS("MCUBOOT")&&RifAwareIPName?starts_with("GPIO")]
					[#list  elmtsListFeatureWithoutGPIO as featureName]
						[#list  featureName as elmtFeatureName]
					 		[#if elmtFeatureName?matches(FeatureName)]
${TABprop}RIFPROT(RIF_${RifAwareIPName?upper_case}${ParamPrefix}${(RifAwareIPName==("IPCC"))?then("("+FeatureName?substring(13)+")",FeatureIDList[FeatureName?index])}, ${MasterCIDList[FeatureName?index]?keep_before_last("|")}, ${(RifAwareIPName == "RCC")?then(LockList[FeatureName?index], "RIF_UNLOCK")}, ${SecureList[FeatureName?index]}, ${PrivilegeList[FeatureName?index]}, ${SCIDList[FeatureName?index]}, ${SemList[FeatureName?index]}, ${FilteringCIDList[FeatureName?index]}) /* Feature = ${FeatureName} */
							[/#if]
						[/#list]
                	[/#list]
                [#elseif (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*") && !RifAwareIPName?matches("HSEM"))]
                    [#if RifAwareIPName?starts_with("HPDMA")||RifAwareIPName?starts_with("FMC")]
                    [#--locking HPDMA,FMC--]
${TABprop}RIFPROT(RIF_${RifAwareIPName?upper_case}${ParamPrefix}${(RifAwareIPName==("IPCC"))?then("("+FeatureName?substring(13)+")",FeatureIDList[FeatureName?index])}, ${MasterCIDList[FeatureName?index]?keep_before_last("|")}, ${(RifAwareIPName == "RCC")?then(LockList[FeatureName?index], "RIF_LOCK")}, ${SecureList[FeatureName?index]}, ${PrivilegeList[FeatureName?index]}, ${SCIDList[FeatureName?index]}, ${SemList[FeatureName?index]}, ${FilteringCIDList[FeatureName?index]}) /* Feature = ${FeatureName} */
                    [#else]
${TABprop}RIFPROT(RIF_${RifAwareIPName?upper_case}${ParamPrefix}${(RifAwareIPName==("IPCC"))?then("("+FeatureName?substring(13)+")",FeatureIDList[FeatureName?index])}, ${MasterCIDList[FeatureName?index]?keep_before_last("|")}, ${(RifAwareIPName == "RCC")?then(LockList[FeatureName?index], "RIF_UNLOCK")}, ${SecureList[FeatureName?index]}, ${PrivilegeList[FeatureName?index]}, ${SCIDList[FeatureName?index]}, ${SemList[FeatureName?index]}, ${FilteringCIDList[FeatureName?index]}) /* Feature = ${FeatureName} */
                    [/#if]
                [#elseif (srvcmx_isTargetedFw_inDTS("OP-TEE") && mx_tdcidContext?matches("A[0-9][0-9].*"))]
${TABprop}RIFPROT(RIF_${RifAwareIPName?upper_case}${ParamPrefix}${(RifAwareIPName==("IPCC"))?then("("+FeatureName?substring(13)+")",FeatureIDList[FeatureName?index])}, ${MasterCIDList[FeatureName?index]?keep_before_last("|")}, ${(RifAwareIPName == "RCC")?then(LockList[FeatureName?index], "RIF_UNLOCK")}, ${SecureList[FeatureName?index]}, ${PrivilegeList[FeatureName?index]}, ${SCIDList[FeatureName?index]}, ${SemList[FeatureName?index]}, ${FilteringCIDList[FeatureName?index]}) /* Feature = ${FeatureName} */
                [/#if]
			[/#list]
            [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*") && !RifAwareIPName?matches("HSEM")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
${TABnode}>;
            [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && (RifAwareIPName?starts_with("GPIO"))]
${TABnode}>;
            [/#if]
[#--here to add specefic property : RifAwareIPName==TAMP,HSEM,EXTI?... --]
            [#if RifAwareIPsWithSpeceficProp?seq_contains(RifAwareIPName)]
                [#list mx_RIF_Params.entrySet() as RIF_Params]
                    [#if (RIF_Params.key)?? && RIF_Params.key?matches("^"+RifAwareExtraTablePrefix+RifAwareIPName)]
                        [#compress]
                            [#assign RifAwareExtraTable = RIF_Params.value]
                            [#assign NbBackupRegistres=[]]
                            [#list RifAwareExtraTable.entrySet() as RifAwareExtraTableList]
                                [#assign NbBackupRegistres+=RifAwareExtraTableList.value]
                            [/#list]
                        [/#compress]
                    [/#if]
                [/#list]
                [#assign RifAware_values =""]
                [#list NbBackupRegistres as nbreBackupRegistres]
                    [#if RifAwareIPName=="TAMP"]
                        [#assign RifAware_values += nbreBackupRegistres + " "]
                    [#else]
                        [#assign RifAware_values += "<"+nbreBackupRegistres + " RIF_CID"+nbreBackupRegistres + ">, "]
                    [/#if]
                [/#list]
                [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*") && !RifAwareIPName?matches("HSEM")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
${TABnode}${(RifAwareIPName=="TAMP")?then("st,backup-zones = <"+RifAware_values?substring(0,RifAware_values?length-1)+">;","st,proccid = <1 RIF_CID1>, <2 RIF_CID2>;")}[#-- <3 RIF_CID3> not supported for Beta3 --]
                [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") &&  RifAwareIPName=="TAMP"]
${TABnode}${(RifAwareIPName=="TAMP")?then("st,backup-zones = <"+RifAware_values?substring(0,RifAware_values?length-1)+">;","st,proccid = <2 RIF_CID2>;")}[#-- <3 RIF_CID3> not supported for Beta3 --]
                [/#if]
                [#if mx_isAhbErrata && supportAhbErrataList?seq_contains(RifAwareIPName)]
${TABnode}st,errata-ahbrisab;
                [/#if]
            [/#if]
            [#if (srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*") && !RifAwareIPName?matches("HSEM")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*"))]
};
            [#elseif srvcmx_isTargetedFw_inDTS("MCUBOOT") && (RifAwareIPName?starts_with("GPIO")||RifAwareIPName?starts_with("TAMP"))]
};
            [/#if]
		[/#if]
	[/#if]
[/#list]
#n
[#if (!mx_socPtCPN?starts_with("stm32mp23")&&!mx_socPtCPN?starts_with("stm32mp21"))&& ((srvcmx_isTargetedFw_inDTS("TF-M") && mx_tdcidContext?matches("M[0-9][0-9].*")) || (srvcmx_isTargetedFw_inDTS("OP-TEE")&&mx_tdcidContext?matches("A[0-9][0-9].*")))]
&ipcc2 {
	st,protreg = <
		RIFPROT(RIF_IPCC_CPU1_CHANNEL(1), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID3, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU1 channel 1 */
		RIFPROT(RIF_IPCC_CPU2_CHANNEL(1), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID1, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU2 channel 1 */
		RIFPROT(RIF_IPCC_CPU1_CHANNEL(2), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID3, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU1 channel 2 */
		RIFPROT(RIF_IPCC_CPU2_CHANNEL(2), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID1, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU2 channel 2 */
		RIFPROT(RIF_IPCC_CPU1_CHANNEL(3), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID3, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU1 channel 3 */
		RIFPROT(RIF_IPCC_CPU2_CHANNEL(3), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID1, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU2 channel 3 */
		RIFPROT(RIF_IPCC_CPU1_CHANNEL(4), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID3, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU1 channel 4 */
		RIFPROT(RIF_IPCC_CPU2_CHANNEL(4), RIF_UNUSED, RIF_UNLOCK, RIF_NSEC, RIF_NPRIV, RIF_CID1, RIF_SEM_DIS, RIF_CFEN) /* Feature = CPU2 channel 4 */
	>;
};
[/#if]


