[#ftl]
[#--STM32-RPROC binding--]
[#--///////////////////--]
[#macro bind_stm32_rproc	pElmt pDtLevel]
	[#compress]
		[#local Tabulation=dts_get_tabs(pDtLevel)]
		[#local TABnode = Tabulation.TABN]
		[#local TABprop = Tabulation.TABP]
		[#local deviceFwName = srvcmx_getFwNameOfBindedDevice_inDTS("ipcc1")]
		[#local vq0=""]
		[#local vq1=""]
		[#local shutdown=""]
		[#local mboxesValue=""]
		[#local mboxNamesValue=[]]
		[#list mx_IpccEnabledModes.entrySet() as IpccEnabledModesMap]
			[#list IpccEnabledModesMap.value as IpccEnabledModesValue]
				[#if (vq0?length==0) && (IpccEnabledModesValue)?matches("Vq0.*")]
					[#local vq0= (IpccEnabledModesValue?matches(".*Interrupt_mode"))?then("0x100","0")]
				[/#if]
				[#if (vq1?length==0) && (IpccEnabledModesValue)?matches("Vq1.*")]
					[#local vq1= (IpccEnabledModesValue?matches(".*Interrupt_mode"))?then("0x101","1")]
				[/#if]
				[#if (shutdown?length==0) && (IpccEnabledModesValue)?matches("ShutDown.*")]
					[#local shutdown= 2][#--only normal mode is available for shutdown--]
				[/#if]
			[/#list]
			[#local IpccInstance = IpccEnabledModesMap.key?lower_case]
		[#local mboxesValue =  (vq0?length>0)?then("<&"+IpccInstance+" "+vq0+">, " , "")+ (vq1?length>0)?then("<&"+IpccInstance+" "+vq1+">, " , "") + (shutdown?length>0)?then("<&"+IpccInstance+" "+shutdown+">, " , "")]
		[#local mboxNamesValue = (vq0?length>0)?then('"vq0", ','')+(vq1?length>0)?then('"vq1", ','')+(shutdown?length>0)?then('"shutdown", ','')]
		[/#list]
	[/#compress]
	[#if srvcmx_isDeviceEnabled("ipcc1") && deviceFwName?has_content]
#n
${TABnode}/*Restriction: "memory-region" property is not managed - please to use User-Section if needed*/
	[/#if]
	[#if mboxNamesValue?has_content]
${TABnode}mboxes = ${mboxesValue?keep_before_last(',')};
${TABnode}mbox-names = ${mboxNamesValue?keep_before_last(',')};
	[/#if]
[/#macro]
