const FAMILY_FILES = {
  stm32f4: './data/stm32f4.json',
  stm32h7: './data/stm32h7.json'
};

const el = {
  family: document.querySelector('#family'),
  soc: document.querySelector('#soc'),
  ptype: document.querySelector('#ptype'),
  instance: document.querySelector('#instance'),
  txMap: document.querySelector('#tx-map'),
  rxMap: document.querySelector('#rx-map'),
  priority: document.querySelector('#priority'),
  mode: document.querySelector('#mode'),
  generate: document.querySelector('#generate'),
  share: document.querySelector('#share'),
  status: document.querySelector('#status'),
  dbVersion: document.querySelector('#db-version'),
  overlayOut: document.querySelector('#overlay-out'),
  prjconfOut: document.querySelector('#prjconf-out'),
  checksOut: document.querySelector('#checks-out')
};

const state = {
  db: {},
  currentFamily: 'stm32f4'
};

function setStatus(message, type = '') {
  el.status.textContent = message;
  el.status.className = `status ${type}`.trim();
}

async function loadDb(family) {
  const path = FAMILY_FILES[family];
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(`Could not load data file: ${path}`);
  }
  const data = await response.json();
  state.db[family] = data;
  return data;
}

function option(value, label) {
  const opt = document.createElement('option');
  opt.value = value;
  opt.textContent = label;
  return opt;
}

function fillFamilies() {
  el.family.innerHTML = '';
  Object.keys(FAMILY_FILES).forEach((family) => {
    el.family.append(option(family, family.toUpperCase()));
  });
}

function fillSocs(db) {
  el.soc.innerHTML = '';
  db.soc.forEach((soc) => el.soc.append(option(soc, soc)));
}

function fillInstances(db) {
  const type = el.ptype.value;
  el.instance.innerHTML = '';
  (db.peripherals[type] || []).forEach((name) => {
    el.instance.append(option(name, name));
  });
}

function mapLabel(m) {
  const req = m.request === null ? 'no-req' : `req=${m.request}`;
  return `${m.controller} stream${m.stream} ch${m.channel} ${req}`;
}

function fillMappings(db) {
  const instance = el.instance.value;
  const tx = db.mappings.filter((m) => m.peripheral === instance && m.direction === 'tx');
  const rx = db.mappings.filter((m) => m.peripheral === instance && m.direction === 'rx');

  el.txMap.innerHTML = '';
  el.rxMap.innerHTML = '';

  tx.forEach((m, idx) => el.txMap.append(option(String(idx), mapLabel(m))));
  rx.forEach((m, idx) => el.rxMap.append(option(String(idx), mapLabel(m))));

  if (!tx.length) {
    el.txMap.append(option('', 'No TX mapping found'));
  }
  if (!rx.length) {
    el.rxMap.append(option('', 'No RX mapping found'));
  }
}

function renderDmaFlags(direction) {
  const priorityMap = {
    low: 'STM32_DMA_PRIORITY_LOW',
    medium: 'STM32_DMA_PRIORITY_MEDIUM',
    high: 'STM32_DMA_PRIORITY_HIGH',
    'very-high': 'STM32_DMA_PRIORITY_VERY_HIGH'
  };
  const modeMap = {
    normal: 'STM32_DMA_MODE_NORMAL',
    circular: 'STM32_DMA_MODE_CIRCULAR'
  };

  const dirMacro = direction === 'tx' ? 'STM32_DMA_MEMORY_TO_PERIPH' : 'STM32_DMA_PERIPH_TO_MEMORY';
  return `${dirMacro} | ${priorityMap[el.priority.value]} | ${modeMap[el.mode.value]}`;
}

function renderOverlay(instance, txMap, rxMap) {
  const txReqComment = txMap.request === null ? '' : ` /* request=${txMap.request} */`;
  const rxReqComment = rxMap.request === null ? '' : ` /* request=${rxMap.request} */`;

  return `/* Generated by Zephyr DMA Config Helper */\n` +
    `&${instance} {\n` +
    `  status = "okay";\n` +
    `  dmas = <&${txMap.controller} ${txMap.stream} ${txMap.channel} (${renderDmaFlags('tx')})>${txReqComment},\n` +
    `         <&${rxMap.controller} ${rxMap.stream} ${rxMap.channel} (${renderDmaFlags('rx')})>${rxReqComment};\n` +
    `  dma-names = "tx", "rx";\n` +
    `};\n`;
}

function renderPrjConf() {
  const type = el.ptype.value;
  const lines = [
    '# Generated by Zephyr DMA Config Helper',
    'CONFIG_DMA=y',
    'CONFIG_DMA_STM32=y'
  ];

  if (type === 'uart') {
    lines.push('CONFIG_SERIAL=y');
    lines.push('CONFIG_UART_ASYNC_API=y');
  }
  if (type === 'spi') {
    lines.push('CONFIG_SPI=y');
  }

  return lines.join('\n') + '\n';
}

function validate(instance, txMap, rxMap) {
  const checks = [];
  const warnings = [];
  const errors = [];

  checks.push(`Target family: ${el.family.value}`);
  checks.push(`SoC: ${el.soc.value}`);
  checks.push(`Peripheral: ${instance}`);

  if (!txMap || !rxMap) {
    errors.push('Missing TX and/or RX mapping in local DB.');
  }

  if (txMap && rxMap && txMap.controller === rxMap.controller && txMap.stream === rxMap.stream) {
    errors.push('TX and RX currently use the same DMA stream. Pick different streams.');
  }

  if (txMap && txMap.request !== null) {
    warnings.push('TX request id is present; verify DMAMUX request line in RM and Zephyr docs.');
  }
  if (rxMap && rxMap.request !== null) {
    warnings.push('RX request id is present; verify DMAMUX request line in RM and Zephyr docs.');
  }

  checks.push('Verify peripheral node name matches your board DTS (e.g. &usart2).');
  checks.push('Verify DMA controller node is enabled in board DTS.');
  checks.push('Run a build to confirm property/macros accepted by your Zephyr version.');

  return { checks, warnings, errors };
}

function allMappingsFor(instance, direction) {
  const db = state.db[state.currentFamily];
  return db.mappings.filter((m) => m.peripheral === instance && m.direction === direction);
}

function getSelectedMappings() {
  const instance = el.instance.value;
  const tx = allMappingsFor(instance, 'tx')[Number(el.txMap.value)];
  const rx = allMappingsFor(instance, 'rx')[Number(el.rxMap.value)];
  return { tx, rx };
}

function generate() {
  const instance = el.instance.value;
  const { tx, rx } = getSelectedMappings();
  const result = validate(instance, tx, rx);

  if (result.errors.length) {
    el.overlayOut.textContent = '# Cannot generate due to errors\n' + result.errors.map((e) => `- ${e}`).join('\n');
    el.prjconfOut.textContent = '# Fix errors first\n';
    el.checksOut.textContent = [
      'Errors:',
      ...result.errors.map((e) => `- ${e}`),
      '',
      'Warnings:',
      ...(result.warnings.length ? result.warnings.map((w) => `- ${w}`) : ['- none']),
      '',
      'Checks:',
      ...result.checks.map((c) => `- ${c}`)
    ].join('\n');
    setStatus(`Blocked: ${result.errors[0]}`, 'err');
    return;
  }

  el.overlayOut.textContent = renderOverlay(instance, tx, rx);
  el.prjconfOut.textContent = renderPrjConf();
  el.checksOut.textContent = [
    'Warnings:',
    ...(result.warnings.length ? result.warnings.map((w) => `- ${w}`) : ['- none']),
    '',
    'Checks:',
    ...result.checks.map((c) => `- ${c}`)
  ].join('\n');

  setStatus('Snippets generated.', 'ok');
}

function onTabClick(event) {
  const tabBtn = event.target.closest('.tab');
  if (!tabBtn) return;

  const nextTab = tabBtn.dataset.tab;
  document.querySelectorAll('.tab').forEach((t) => t.classList.toggle('active', t === tabBtn));
  document.querySelectorAll('.tab-content').forEach((panel) => panel.classList.toggle('active', panel.id === nextTab));
}

async function copyText(text) {
  await navigator.clipboard.writeText(text);
}

function download(name, content) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.append(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function attachOutputActions() {
  document.body.addEventListener('click', async (event) => {
    const copyBtn = event.target.closest('[data-copy]');
    if (copyBtn) {
      const targetId = copyBtn.dataset.copy;
      const source = document.getElementById(targetId);
      try {
        await copyText(source.textContent || '');
        setStatus('Copied to clipboard.', 'ok');
      } catch (_err) {
        setStatus('Clipboard access failed.', 'warn');
      }
      return;
    }

    const dlBtn = event.target.closest('[data-download]');
    if (dlBtn) {
      const kind = dlBtn.dataset.download;
      if (kind === 'overlay') download('dma.overlay', el.overlayOut.textContent || '');
      if (kind === 'prjconf') download('prj.conf', el.prjconfOut.textContent || '');
      if (kind === 'checks') download('dma-checks.txt', el.checksOut.textContent || '');
      setStatus('File downloaded.', 'ok');
    }
  });
}

function toQuery() {
  const params = new URLSearchParams({
    family: el.family.value,
    soc: el.soc.value,
    ptype: el.ptype.value,
    instance: el.instance.value,
    tx: el.txMap.value,
    rx: el.rxMap.value,
    priority: el.priority.value,
    mode: el.mode.value
  });
  return `${location.origin}${location.pathname}?${params.toString()}`;
}

function restoreFromQuery() {
  const p = new URLSearchParams(location.search);
  const family = p.get('family');
  if (family && FAMILY_FILES[family]) {
    el.family.value = family;
    state.currentFamily = family;
    return p;
  }
  return p;
}

async function refreshForFamily(query = null) {
  state.currentFamily = el.family.value;
  const db = state.db[state.currentFamily] || (await loadDb(state.currentFamily));
  el.dbVersion.textContent = `DB: ${db.family} @ ${db.version}`;

  fillSocs(db);
  fillInstances(db);
  fillMappings(db);

  if (query) {
    if (query.get('soc')) el.soc.value = query.get('soc');
    if (query.get('ptype')) el.ptype.value = query.get('ptype');

    fillInstances(db);
    if (query.get('instance')) el.instance.value = query.get('instance');

    fillMappings(db);
    if (query.get('tx')) el.txMap.value = query.get('tx');
    if (query.get('rx')) el.rxMap.value = query.get('rx');
    if (query.get('priority')) el.priority.value = query.get('priority');
    if (query.get('mode')) el.mode.value = query.get('mode');
  }
}

async function init() {
  fillFamilies();

  const query = restoreFromQuery();
  await refreshForFamily(query);

  el.family.addEventListener('change', () => refreshForFamily());
  el.ptype.addEventListener('change', () => {
    fillInstances(state.db[state.currentFamily]);
    fillMappings(state.db[state.currentFamily]);
  });
  el.instance.addEventListener('change', () => fillMappings(state.db[state.currentFamily]));

  el.generate.addEventListener('click', generate);
  el.share.addEventListener('click', async () => {
    try {
      await copyText(toQuery());
      setStatus('Share link copied.', 'ok');
    } catch (_err) {
      setStatus('Share link copy failed.', 'warn');
    }
  });

  document.querySelector('.tabs').addEventListener('click', onTabClick);
  attachOutputActions();
  generate();
}

init().catch((err) => {
  setStatus(err.message, 'err');
  el.overlayOut.textContent = '# Failed to initialize app\n' + String(err.message || err);
});
